In [1]:
# Simple Neural Network
weight = 0.1
def neural_network(inp, weight):
    prediction = inp * weight
    return prediction

# Performing prediction 
number_of_toes = [8.5, 9.5, 10, 9]
inp = number_of_toes[0]
pred = neural_network(inp, weight)
pred

0.8500000000000001

In Neural network
- input is information
- weight is knowledge | weight acts as measure of sensitivity for input
- output is prediction

## Making a Prediction with Multiple Inputs


In [2]:
# Network with multiple inputs
weights = [0.1, 0.2, 0]
def neural_network(inp, weights):
    print(inp, weights)
    pred = w_sum(inp, weights)
    return pred

In [3]:
# Input
toes = [8.5, 9.5, 9.9, 9.0]    # number of toest
wlrec = [0.65, 0.8, 0.8, 0.9]  # win/loss percent record
nfans = [1.2, 1.3, 0.5, 1.0]   # in millions 

inp = [toes[0],wlrec[0],nfans[0]]

In [4]:
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += a[i] * b[i]
    return output

In [5]:
weights = [0.1, 0.2, 0] 
pred = neural_network(inp, weights)
pred

[8.5, 0.65, 1.2] [0.1, 0.2, 0]


0.9800000000000001

In [6]:
## Challenge
def elementwise_addition(vec_a, vec_b):
    assert(len(a)==len(b))
    vec_c = []
    for i in range(len(a)):
        vec_c[i] = vec_a[i] + vec_b[i]
    return vec_c

def elementwise_multiplication(vec_a, vec_b):
    assert(len(a)==len(b))
    vec_c = []
    for i in range(len(a)):
        vec_c[i] = vec_a[i] * vec_b[i]
    return vec_c

def vector_sun(vec_a):
    sum = 0
    for i in vec_a:
        sum+=i
    return sum

def vector_average(vec_a):
    sum = 0
    for i in vec_a:
        sum+=i
    return sum/len(vec_a)
    

# Numpy
## Making a Prediction with Multiple Inputs

In [7]:
import numpy as np
weight = np.array([0.1, 0.2, 0])
def neural_network(inp, weights):
    pred = inp.dot(weights)
    return pred

In [8]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

inp = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(inp, weights)
pred

np.float64(0.9800000000000001)

## Making a Prediction with Multiple Outputs using single input

In [9]:
# Instead of predicting just whether the team won or lost, 
# you’re also predicting whether the players are happy or sad
# and the percentage of team members who are hurt. 
# You make this prediction using only the current win/loss record.
weights = [0.3, 0.2, 0.9]
def neural_network(inp, weights):
    pred = ele_mul(inp, weights)
    return pred

In [10]:
def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))
    for i in range(len(output)):
        output[i] = number * vector[i]
    return output

In [11]:
wlrec = [0.65, 0.8, 0.8, 0.9]
inp = wlrec[0]
pred =  neural_network(inp, weights)
pred

[0.195, 0.13, 0.5850000000000001]

## Making a prediction with Multiple outputs using multiple inputs

In [12]:
# a weight connects each input node to each output node,
           #toes %win #fan
weights = [[0.1, 0.1, -0.3], # hurt? 
           [0.1, 0.2, 0.0], # win? 
           [0.0, 1.3, 0.1] ] # sad?
print(len(weights), 'This associates with number of outputs')
def neural_network(inp, weights):
    pred = vect_mat_mul(inp, weights)
    return pred

3 This associates with number of outputs


In [13]:
toes = [8.5, 9.5, 9.9, 9.0] 
wlrec = [0.65,0.8, 0.8, 0.9] 
nfans = [1.2, 1.3, 0.5, 1.0]

# Inserting one input datapoint
inp = [toes[0],wlrec[0],nfans[0]]

In [14]:
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output+= a[i]*b[i]
    return output

def vect_mat_mul(vect,matrix):
    assert(len(vect) == len(matrix))
    output = [0,0,0]
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output

In [15]:
pred = neural_network(inp,weights)
pred

[0.555, 0.9800000000000001, 0.9650000000000001]

In the above architecture, we perform vector_matrix_multiplication which is dot product of vector for each row in matrix

## Predicting on predictions
### Stacking layers

Introducing one hidden layer would result in two vector_matrix_multiplication

In [16]:
        # toes % win # fans 
ih_wgt = [[0.1, 0.2, -0.1], # hid[0]
          [-0.1,0.1, 0.9], # hid[1]
          [0.1, 0.4, 0.1] ] # hid[2]

        #hid[0] hid[1] hid[2] 
hp_wgt = [[0.3, 1.1, -0.3], # hurt? 
          [0.1, 0.2, 0.0], # win?
          [0.0, 1.3, 0.1] ] # sad?

weights = [ih_wgt, hp_wgt]

In [17]:
def neural_network(inp, weights):
    hid = vect_mat_mul(inp, weights[0])
    print(hid)
    pred = vect_mat_mul(hid, weights[1])
    return pred

pred = neural_network(inp, weights)
pred

[0.8600000000000001, 0.29499999999999993, 1.23]


[0.21350000000000002, 0.14500000000000002, 0.5065]

## Numpy Version of hidden layers

In [18]:
import numpy as np
                  #toes %win #fan
ih_wgt = np.array([[0.1, 0.2, -0.1], #hid[0]
                  [-0.1, 0.1, 0.9], #hid[1]
                  [0.1, 0.4, 0.1]]).T  #hid[2]

                # hid[0] hid[1] hid[2]
hp_wgt = np.array([[0.3, 1.1, -0.3], # hurt?
                  [0.1, 0.2, 0.0],  # win?
                  [0.0, 1.3, 0.1]]).T  # sad?

weights = [ih_wgt, hp_wgt]
inp = [toes[0],wlrec[0],nfans[0]]

pred = neural_network(inp, weights)
pred

[np.float64(0.9050000000000001), np.float64(2.245), np.float64(-0.14500000000000002)]


[np.float64(0.49600000000000005),
 np.float64(1.2560000000000002),
 np.float64(-0.28600000000000003)]

In [19]:
def neural_network(inp, weights):
    hid = inp.dot(weights[0])
    print(hid)
    pred = hid.dot(weights[1])
    return pred

In [20]:
toes = np.array(toes)
wlrec = np.array(wlrec)
nfans = np.array(nfans)

inp = np.array(inp)
inp

array([8.5 , 0.65, 1.2 ])

In [21]:
pred = neural_network(inp, weights)
pred

[0.86  0.295 1.23 ]


array([0.2135, 0.145 , 0.5065])

## Multiplication Rules:
### Vector * Matrix Multiplication
Element wise multiplication by matching columns or having single column

In [24]:
np.array([1,2,3]) * np.array([[4,5,6],
                              [7,8,9]])

array([[ 4, 10, 18],
       [ 7, 16, 27]])

In [34]:
np.array([1,2,3]).dot(np.array([[4,5,6],
                              [7,8,9]]))

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

### Matrix * Matrix Multiplication
#### Elementwise Multiplication

In [35]:
a = np.array([[1,2,3],
              [4,5,6]])

In [36]:
b = np.array([[1,2,3],
              [4,5,6]])

In [37]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36]])

#### Matrix Muliplication/Dot product Rules

In [39]:
a.dot(b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

Dot product requires the A<sup>mxn</sup> @ B<sup>nxo</sup>, where n in A and B are equal

### DOT Products

In [46]:
# when two 1-D array are operated using dot product
a = np.array([1,2,3])
a@a

np.int64(14)

In [48]:
# when two 2-D array are operated using dot product then Matrix Multiplication is applied
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[1,2,3],
              [4,5,6]])

In [49]:
a@b.T

array([[14, 32],
       [32, 77]])

In [50]:
# When either is 0-D (Scalar) 
a = 2
b = np.array([3, 4])

result = np.dot(a, b)
print(result)

[6 8]


In [55]:
# when one matrix is N-D and other is 1-D
# Sum product rule is applied

a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([7, 8])

result = np.dot(a, b)
print(result)

[23 53 83]


In [45]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[[5, 6],
               [7, 8]],
              
              [[9, 10],
               [11, 12]]])

result = np.dot(a, b)
print(result)

[[[19 22]
  [31 34]]

 [[43 50]
  [71 78]]]
